import React from "react";
import Head from "next/head";
import { useState, useEffect } from "react";
import Section from "./Section";
export default function Contact() {
  let [phoneOnglets, setPhoneOnglets] = useState(false);
  let [phoneSearchOnglet, setPhoneSearchOnglet] = useState(false);
  let [phoneSwitch, setPhoneSwitch] = useState([1, 0, 0]);
  //
  let [dateStamp, setDateStamp] = useState(0);
  let [switchView, setSwitchView] = useState(false);
  let [auteur, setAuteur] = useState("");
  let [validAuteur, setValidAuteur] = useState(false);
  let [categorie, setCategorie] = useState("");
  let [validCategorie, setValidCategorie] = useState(false);
  let [titre, setTitre] = useState("");
  let [validTitre, setValidTitre] = useState(false);
  let [resume, setResume] = useState("");
  let [validResume, setValidResume] = useState(false);
  let [sections, setSections] = useState([]);
  let [JSONcode, setJSONCode] = useState("");
  let [downloadLink, setDownloadLink] = useState("");
  const updateJSONCode = () => {
    return JSON.stringify({
      datestamp: dateStamp,
      auteur: auteur,
      categorie: categorie,
      titre: titre,
      resume: resume,
      sections: sections,
    });
  };
  const createLink = () => {
    setDateStamp(new Date().getTime());
    setDownloadLink(`${categorie}__${auteur}__${dateStamp}`);
  };
  useEffect(() => {
    let res = updateJSONCode();
    setJSONCode(res);
    createLink();
  }, [auteur, categorie, titre, resume, sections]);
  return (
    <>
      <Head>
        <title>Tout est NET : Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div id="background">
          <div className="blob" id="blob1">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#D6D6D6"
                d="M57.8,-44.6C73.7,-26.2,84.4,-2.2,80.6,19.9C76.7,42,58.2,62.2,35.5,72.6C12.9,83.1,-13.9,83.8,-33.8,73.1C-53.7,62.4,-66.8,40.3,-72.5,16.2C-78.2,-7.8,-76.7,-33.8,-63.4,-51.7C-50.1,-69.5,-25,-79.2,-2,-77.6C21,-76,41.9,-63.1,57.8,-44.6Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
          <div className="blob" id="blob2">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#7DD8F6"
                d="M63.1,-51.4C75.1,-35.4,73.3,-9.5,64.6,9.1C55.9,27.8,40.2,39.3,21.2,51.1C2.3,63,-19.9,75.2,-35.3,69.3C-50.7,63.4,-59.3,39.5,-65.2,14.7C-71,-10.2,-74.1,-35.8,-62.7,-51.7C-51.4,-67.5,-25.7,-73.6,-0.1,-73.5C25.6,-73.5,51.2,-67.4,63.1,-51.4Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
          <div className="blob" id="blob3">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#D6D6D6"
                d="M31.8,-49.9C40.5,-37.4,46.6,-27.2,53.7,-15.1C60.8,-3,68.9,11,66,21.9C63.2,32.9,49.2,40.7,36.3,47C23.5,53.3,11.7,58.1,0.9,56.8C-9.9,55.6,-19.7,48.2,-33.3,42.1C-46.9,36,-64.2,31.3,-69.5,21.1C-74.8,11,-68,-4.4,-60.6,-17.3C-53.2,-30.2,-45.1,-40.5,-34.8,-52.6C-24.6,-64.6,-12.3,-78.3,-0.4,-77.8C11.5,-77.2,23,-62.4,31.8,-49.9Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
          <div className="blob" id="blob4">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#7DD8F6"
                d="M37.6,-1.3C37.6,21.8,18.8,43.6,0.4,43.6C-18,43.6,-36,21.8,-36,-1.3C-36,-24.4,-18,-48.7,0.4,-48.7C18.8,-48.7,37.6,-24.4,37.6,-1.3Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
          <div className="blob" id="blob5">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#D6D6D6"
                d="M53,-40.4C58.4,-35.6,45.1,-14.2,37.7,4.6C30.2,23.3,28.4,39.4,19.7,45.3C10.9,51.2,-4.8,47,-15.9,39.3C-26.9,31.5,-33.2,20.3,-37.7,6.8C-42.2,-6.7,-45,-22.4,-38.4,-27.5C-31.9,-32.5,-15.9,-27,4,-30.1C23.9,-33.3,47.7,-45.2,53,-40.4Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
          <div className="blob" id="blob6">
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#7DD8F6"
                d="M58.3,-39.2C71.8,-29.5,76.5,-5.5,68.1,9.2C59.7,23.9,38.2,29.4,20,36C1.8,42.6,-13.1,50.4,-30.7,48C-48.4,45.6,-68.7,33,-74.8,14.6C-80.9,-3.7,-72.8,-27.6,-58,-37.6C-43.1,-47.6,-21.6,-43.5,0.4,-43.9C22.4,-44.2,44.7,-48.8,58.3,-39.2Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
        </div>
        <div id="frontground">
          <div id="header">
            <div id="header-top">
              <div id="logo">
                <div
                  id="hide-icon"
                  onClick={() => {
                    setPhoneOnglets(!phoneOnglets);
                  }}
                >
                  Hide
                </div>
                <div>
                  <a
                    href={"/"}
                    style={{
                      textDecoration: "none",
                      cursor: "pointer",
                      color: "inherit",
                    }}
                  >
                    Tout Est Net
                  </a>
                </div>
              </div>
              <div
                id="onglets-phone"
                style={{ left: phoneOnglets ? "0%" : "-100%" }}
              >
                <div
                  className="onglets back"
                  onClick={() => {
                    setPhoneOnglets(!phoneOnglets);
                  }}
                >
                  Retour
                </div>
                <div className="onglets accueil">
                  <a
                    href={"/"}
                    style={{
                      textDecoration: "none",
                      cursor: "pointer",
                      color: "inherit",
                    }}
                  >
                    Accueil
                  </a>
                </div>
                {/*onglets des categories  */}
                <div className="onglets contact">
                  <a
                    href={"/contact"}
                    style={{
                      textDecoration: "none",
                      cursor: "pointer",
                      color: "inherit",
                    }}
                  >
                    Contact
                  </a>
                </div>
                <div
                  className="onglets recherche"
                  onClick={() => {
                    setPhoneSearchOnglet(!phoneSearchOnglet);
                  }}
                >
                  Recherche
                </div>
              </div>
              <div
                id="article-search-phone"
                style={{ top: phoneSearchOnglet ? "0%" : "-100%" }}
              >
                <div
                  id="search-back"
                  onClick={() => {
                    setPhoneSearchOnglet(!phoneSearchOnglet);
                  }}
                >
                  <div>Retour</div>
                </div>
                <div id="search-input">
                  <input type="text"></input>
                  <div id="valid-search">&#128269;</div>
                </div>
                <div id="liste-search"></div>
              </div>
              <div id="onglets-computer">
                <div className="onglets accueil">
                  <a
                    href={"/"}
                    style={{
                      textDecoration: "none",
                      cursor: "pointer",
                      color: "inherit",
                    }}
                  >
                    Accueil
                  </a>
                </div>
                <div className="onglets contact">
                  <a
                    href={"/contact"}
                    style={{
                      textDecoration: "none",
                      cursor: "pointer",
                      color: "inherit",
                    }}
                  >
                    Contact
                  </a>
                </div>
              </div>
            </div>
            <div id="header-bottom">{/*onglets des categories  */}</div>
          </div>
          <div id="edit-phone">
            <div id="edit-switch">
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr",
                  alignItems: "center",
                  justifyItems: "center",
                  backgroundColor: phoneSwitch[0] ? "#7dd8f6" : "inherit",
                  fontWeight: phoneSwitch[0] ? "bold" : "inherit",
                }}
                onClick={(e) => {
                  setPhoneSwitch([1, 0, 0]);
                }}
              >
                <div>Creer article</div>
              </div>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr",
                  alignItems: "center",
                  justifyItems: "center",
                  backgroundColor: phoneSwitch[1] ? "#7dd8f6" : "inherit",
                  fontWeight: phoneSwitch[1] ? "bold" : "inherit",
                }}
                onClick={(e) => {
                  setPhoneSwitch([0, 1, 0]);
                }}
              >
                <div>Voir article</div>
              </div>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr",
                  alignItems: "center",
                  justifyItems: "center",
                  backgroundColor: phoneSwitch[2] ? "#7dd8f6" : "inherit",
                  fontWeight: phoneSwitch[2] ? "bold" : "inherit",
                }}
                onClick={(e) => {
                  setPhoneSwitch([0, 0, 1]);
                }}
              >
                <div>Voir Code</div>
              </div>
            </div>
            <div
              id="edit-field"
              style={{ display: phoneSwitch[0] ? "block" : "none" }}
            >
              <div id="edit-author">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                  }}
                >
                  Entrez le nom de l'auteur
                </div>
                <div
                  style={{ display: "grid", gridTemplateColumns: "80% 20%" }}
                >
                  <div
                    style={{
                      display: "grid",
                      gridTemplateRows: "repeat(2,1fr)",
                      width: "100%",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    {!validAuteur ? (
                      <>
                        <div style={{ width: "96%", marginLeft: "2%" }}>
                          <select
                            onChange={(e) => {
                              setAuteur(e.target.value);
                            }}
                            style={{ width: "96%", marginLeft: "2%" }}
                          >
                            <option>Choisissez un auteur</option>
                          </select>
                        </div>
                        <div style={{ width: "96%", marginLeft: "2%" }}>
                          <input
                            onChange={(e) => {
                              setAuteur(e.target.value);
                            }}
                            type="text"
                            style={{ width: "96%", marginLeft: "2%" }}
                            placeholder="entrez le nom de l'auteur"
                          ></input>
                        </div>
                      </>
                    ) : (
                      <>
                        <div>{auteur}</div>
                      </>
                    )}
                  </div>
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    <button
                      onClick={(e) => {
                        setValidAuteur(!validAuteur);
                      }}
                    >
                      {validAuteur ? "Modifier" : "Confirmer"}
                    </button>
                  </div>
                </div>
              </div>
              <div id="edit-categorie">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                  }}
                >
                  Entrez le nom de la categorie
                </div>
                <div
                  style={{ display: "grid", gridTemplateColumns: "80% 20%" }}
                >
                  <div
                    style={{
                      display: "grid",
                      gridTemplateRows: "repeat(2,1fr)",
                      width: "100%",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    {!validCategorie ? (
                      <>
                        <div style={{ width: "96%", marginLeft: "2%" }}>
                          <select
                            onChange={(e) => {
                              setCategorie(e.target.value);
                            }}
                            style={{ width: "96%", marginLeft: "2%" }}
                          >
                            <option>Choisissez un auteur</option>
                          </select>
                        </div>
                        <div style={{ width: "96%", marginLeft: "2%" }}>
                          <input
                            onChange={(e) => {
                              setCategorie(e.target.value);
                            }}
                            type="text"
                            style={{ width: "96%", marginLeft: "2%" }}
                            placeholder="entrez le nom de l'auteur"
                          ></input>
                        </div>
                      </>
                    ) : (
                      <>
                        <div>{categorie}</div>
                      </>
                    )}
                  </div>
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    <button
                      onClick={(e) => {
                        setValidCategorie(!validCategorie);
                      }}
                    >
                      {validCategorie ? "Modifier" : "Confirmer"}
                    </button>
                  </div>
                </div>
              </div>
              <div id="edit-titre">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                  }}
                >
                  Entrez le titre de votre article
                </div>
                <div
                  style={{ display: "grid", gridTemplateColumns: "80% 20%" }}
                >
                  <div
                    style={{
                      display: "grid",
                      gridTemplateRows: "1fr",
                      width: "100%",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    {!validTitre ? (
                      <>
                        <textarea
                          style={{ width: "96%", marginLeft: "2%" }}
                        ></textarea>
                      </>
                    ) : (
                      <>
                        <div>{titre}</div>
                      </>
                    )}
                  </div>
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    <button
                      onClick={(e) => {
                        setValidTitre(!validTitre);
                      }}
                    >
                      {validTitre ? "Modifier" : "Confirmer"}
                    </button>
                  </div>
                </div>
              </div>
              <div id="edit-resume">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                  }}
                >
                  Entrez le resume de votre article
                </div>
                <div
                  style={{ display: "grid", gridTemplateColumns: "80% 20%" }}
                >
                  <div
                    style={{
                      display: "grid",
                      gridTemplateRows: "1fr",
                      width: "100%",
                      height: "100%",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    {!validResume ? (
                      <>
                        <textarea
                          style={{
                            width: "96%",
                            height: "80%",
                            marginLeft: "2%",
                            marginTop: "2%",
                          }}
                          onChange={(e) => {
                            setResume(e.target.value);
                          }}
                        ></textarea>
                      </>
                    ) : (
                      <>
                        <div>{resume}</div>
                      </>
                    )}
                  </div>
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr",
                      justifyItems: "center",
                      alignItems: "center",
                    }}
                  >
                    <button
                      onClick={(e) => {
                        setValidResume(!validResume);
                      }}
                    >
                      {validResume ? "Modifier" : "Confirmer"}
                    </button>
                  </div>
                </div>
              </div>
              {sections.map((el, index) => (
                <Section
                  key={index}
                  index={index}
                  sections={sections}
                  setSections={setSections}
                ></Section>
              ))}
              <div
                style={{
                  height: "60px",
                  width: "100%",
                  boxSizing: "border-box",
                  border: "2px solid black",
                  marginBottom: "5px",
                  marginTop: "5px",
                  display: "grid",
                  gridTemplateRows: "repeat(2,1fr)",
                }}
              >
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  Ajouter une section a votre article
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  <button
                    onClick={(e) => {
                      setSections([...sections, {}]);
                    }}
                  >
                    Ajouter
                  </button>
                </div>
              </div>
            </div>
            <div
              id="view-article-field"
              style={{ display: phoneSwitch[1] ? "block" : "none" }}
            >
              <div
                id="view-author"
                style={{
                  border: validAuteur
                    ? "2px solid rgba(29, 183, 5,.8)"
                    : "2px solid black",
                  backgroundColor: validAuteur
                    ? "rgba(29, 183, 5,.3)"
                    : "inherit",
                }}
              >
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                    borderBottom: validAuteur
                      ? "2px solid rgba(29, 183, 5,.3)"
                      : "2px solid black",
                  }}
                >
                  Auteur :
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  {auteur}
                </div>
              </div>
              <div
                id="view-categorie"
                style={{
                  border: validCategorie
                    ? "2px solid rgba(29, 183, 5,.8)"
                    : "2px solid black",
                  backgroundColor: validCategorie
                    ? "rgba(29, 183, 5,.3)"
                    : "inherit",
                }}
              >
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                    borderBottom: validCategorie
                      ? "2px solid rgba(29, 183, 5,.3)"
                      : "2px solid black",
                  }}
                >
                  Categorie :
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  {categorie}
                </div>
              </div>
              <div
                id="view-titre"
                style={{
                  border: validTitre
                    ? "2px solid rgba(29, 183, 5,.8)"
                    : "2px solid black",
                  backgroundColor: validTitre
                    ? "rgba(29, 183, 5,.3)"
                    : "inherit",
                }}
              >
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                    borderBottom: validTitre
                      ? "2px solid rgba(29, 183, 5,.3)"
                      : "2px solid black",
                  }}
                >
                  Titre :
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  {titre}
                </div>
              </div>
              <div
                id="view-resume"
                style={{
                  border: validResume
                    ? "2px solid rgba(29, 183, 5,.8)"
                    : "2px solid black",
                  backgroundColor: validResume
                    ? "rgba(29, 183, 5,.3)"
                    : "inherit",
                }}
              >
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                    borderBottom: validResume
                      ? "2px solid rgba(29, 183, 5,.3)"
                      : "2px solid black",
                  }}
                >
                  Resume :
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    justifyItems: "center",
                    alignItems: "center",
                  }}
                >
                  {resume}
                </div>
              </div>
              {sections.length ? (
                <div id="view-sommaire">
                  <div
                    style={{
                      display: "grid",
                      gridTemplateColumns: "1fr",
                      alignItems: "center",
                      justifyItems: "center",
                      borderBottom: "2px solid black",
                    }}
                  >
                    Sommaire
                  </div>
                  <ol style={{ marginLeft: "5px", marginRight: "5px" }}>
                    {sections.map((el, index) => (
                      <li
                        key={index}
                        style={{ marginTop: "3px", marginBottom: "3px" }}
                      >
                        <a
                          href={`#section-${index}`}
                          className="liste-sommaire"
                        >
                          {el.titre}
                        </a>
                      </li>
                    ))}
                  </ol>
                </div>
              ) : (
                <></>
              )}
              {sections.length ? (
                <div id="view-sections">
                  {sections.map((el, index) => (
                    <div
                      key={index}
                      className="section"
                      id={`section-${index}`}
                      style={{
                        backgroundColor: el.valide
                          ? "rgba(29, 183, 5,.3)"
                          : "inherit",
                        border: el.valide
                          ? "2px solid rgba(29, 183, 5,.8)"
                          : "none",
                      }}
                    >
                      <div className="paragraphe-titre">{el.titre}</div>
                      {el?.paragraphes?.map((element, id) => (
                        <>
                          <div
                            key={id}
                            className="paragraphe"
                            dangerouslySetInnerHTML={{ __html: element }}
                          ></div>
                        </>
                      ))}
                    </div>
                  ))}
                </div>
              ) : (
                <></>
              )}
            </div>
            <div
              id="view-code-field"
              style={{
                display: phoneSwitch[2] ? "block" : "none",
                height: "100%",
              }}
            >
              <textarea
                style={{
                  width: "96%",
                  marginLeft: "2%",
                  marginTop: "5px",
                  height: "80%",
                }}
                value={JSONcode}
              ></textarea>
              <div style={{ marginLeft: "2%" }}>
                <button>Copier</button>
                <button>
                  <a
                    className="liste-sommaire"
                    href={globalThis?.window?.URL?.createObjectURL(
                      new Blob([JSONcode], { type: "application/json" })
                    )}
                    download={`${downloadLink}.json`}
                  >
                    Enregistrer
                  </a>
                </button>
              </div>
            </div>
          </div>
          <div id="edit-computer">
            <div id="edit-field">
              <div id="edit-author">
                <div id="edit-header">
                  Entrez ou selectionnez le nom de l'auteur
                </div>
                <div id="edit-textArea">
                  {!validAuteur ? (
                    <>
                      <select
                        style={{ width: "80%" }}
                        onChange={(e) => {
                          setAuteur(e.target.value);
                        }}
                      >
                        <option>Choisissez un auteur</option>
                        {}
                      </select>
                      <input
                        type="text"
                        style={{ width: "80%" }}
                        onChange={(e) => {
                          setAuteur(e.target.value);
                        }}
                      ></input>
                    </>
                  ) : (
                    <>
                      <div>{auteur}</div>
                    </>
                  )}
                </div>
                <div id="edit-confirm">
                  <button
                    onClick={(e) => {
                      setValidAuteur(!validAuteur);
                    }}
                  >
                    {validAuteur ? "Modifier" : "Confirmer"}
                  </button>
                </div>
              </div>
              <div id="edit-categorie">
                <div id="edit-header">Entrez la categorie de votre article</div>
                <div id="edit-textArea">
                  {!validCategorie ? (
                    <>
                      <select
                        style={{ width: "80%" }}
                        onChange={(e) => {
                          setCategorie(e.target.value);
                        }}
                      >
                        <option>Choisissez un auteur</option>
                        {}
                      </select>
                      <input
                        type="text"
                        style={{ width: "80%" }}
                        onChange={(e) => {
                          setCategorie(e.target.value);
                        }}
                      ></input>
                    </>
                  ) : (
                    <>
                      <div>{categorie}</div>
                    </>
                  )}
                </div>
                <div id="edit-confirm">
                  <button
                    onClick={(e) => {
                      setValidCategorie(!validCategorie);
                    }}
                  >
                    {validCategorie ? "Modifier" : "Confirmer"}
                  </button>
                </div>
              </div>
              <div id="edit-titre">
                <div id="edit-header">Entrez le titre de votre article</div>
                <div id="edit-textArea">
                  {!validTitre ? (
                    <>
                      <input
                        type="text"
                        style={{ width: "80%" }}
                        onChange={(e) => {
                          setTitre(e.target.value);
                        }}
                      ></input>
                    </>
                  ) : (
                    <>
                      <div>{titre}</div>
                    </>
                  )}
                </div>
                <div id="edit-confirm">
                  <button
                    onClick={(e) => {
                      setValidTitre(!validTitre);
                    }}
                  >
                    {validTitre ? "Modifier" : "Confirmer"}
                  </button>
                </div>
              </div>
              <div id="edit-resume">
                <div id="edit-header">Entrez le resume de votre article</div>
                <div id="edit-textArea">
                  {!validResume ? (
                    <>
                      <textarea
                        style={{ width: "100%", height: "100%" }}
                        onChange={(e) => {
                          setResume(e.target.value);
                        }}
                      ></textarea>
                    </>
                  ) : (
                    <>
                      <div>{resume}</div>
                    </>
                  )}
                </div>
                <div id="edit-confirm">
                  <button
                    onClick={(e) => {
                      setValidResume(!validResume);
                    }}
                  >
                    {validResume ? "Modifier" : "Confirmer"}
                  </button>
                </div>
              </div>
              {sections.map((el, index) => (
                <Section
                  key={index}
                  index={index}
                  sections={sections}
                  setSections={setSections}
                ></Section>
              ))}
              <div id="edit-section">
                <div>Ajouter une section a votre article</div>
                <div>
                  <button
                    onClick={(e) => {
                      setSections([...sections, {}]);
                    }}
                  >
                    Ajouter
                  </button>
                </div>
              </div>
            </div>
            <div id="view-field">
              <div id="view-field-switch">
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                    backgroundColor: !switchView ? "#7dd8f6" : "inherit",
                    fontWeight: switchView ? "inherit" : "bold",
                  }}
                  onClick={(e) => {
                    switchView === false
                      ? setSwitchView(switchView)
                      : setSwitchView(!switchView);
                  }}
                >
                  Vue article
                </div>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr",
                    alignItems: "center",
                    justifyItems: "center",
                    backgroundColor: !switchView ? "inherit" : "#7dd8f6",
                    fontWeight: switchView ? "bold" : "inherit",
                  }}
                  onClick={(e) => {
                    switchView === true
                      ? setSwitchView(switchView)
                      : setSwitchView(!switchView);
                  }}
                >
                  Vue code
                </div>
              </div>
              <div
                id="view-field-show"
                style={{ display: !switchView ? "block" : "none" }}
              >
                <div
                  id="view-author"
                  style={{
                    backgroundColor: validAuteur
                      ? "rgba(29, 183, 5,.3)"
                      : "inherit",
                    border: validAuteur
                      ? "2px solid rgba(29, 183, 5,.8)"
                      : "none",
                  }}
                >
                  <div style={{ paddingLeft: "5px" }}>Auteur :</div>
                  <div>{auteur}</div>
                </div>
                <div
                  id="view-categorie"
                  style={{
                    backgroundColor: validCategorie
                      ? "rgba(29, 183, 5,.3)"
                      : "inherit",
                    border: validCategorie
                      ? "2px solid rgba(29, 183, 5,.8)"
                      : "none",
                  }}
                >
                  <div style={{ paddingLeft: "5px" }}>Categorie :</div>
                  <div>{categorie}</div>
                </div>
                <div
                  id="view-titre"
                  style={{
                    backgroundColor: validTitre
                      ? "rgba(29, 183, 5,.3)"
                      : "inherit",
                    border: validTitre
                      ? "2px solid rgba(29, 183, 5,.8)"
                      : "none",
                  }}
                >
                  <div style={{ paddingLeft: "5px" }}>Titre :</div>
                  <div>{titre}</div>
                </div>
                <div
                  id="view-resume"
                  style={{
                    backgroundColor: validResume
                      ? "rgba(29, 183, 5,.3)"
                      : "inherit",
                    border: validResume
                      ? "2px solid rgba(29, 183, 5,.8)"
                      : "none",
                  }}
                >
                  <div
                    style={{ textAlign: "center", textDecoration: "underline" }}
                  >
                    Resume de l'article
                  </div>
                  <div style={{ padding: "5px" }}>{resume}</div>
                </div>
                {sections.length ? (
                  <div id="view-sommaire">
                    <div
                      style={{
                        textAlign: "center",
                        textDecoration: "underline",
                        fontWeight: "bold",
                      }}
                    >
                      Sommaire
                    </div>
                    <ol
                      style={{
                        border: "2px solid black",
                        borderRadius: "5px",
                        paddingTop: "5px",
                      }}
                    >
                      {sections.map((el, index) => (
                        <li key={index}>
                          <a
                            href={`#section-${index}`}
                            className="liste-sommaire"
                          >
                            {el.titre}
                          </a>
                        </li>
                      ))}
                    </ol>
                  </div>
                ) : (
                  <></>
                )}
                {sections.length ? (
                  <div id="view-sections">
                    {sections.map((el, index) => (
                      <div
                        key={index}
                        className="section"
                        style={{
                          backgroundColor: el.valide
                            ? "rgba(29, 183, 5,.3)"
                            : "inherit",
                          border: el.valide
                            ? "2px solid rgba(29, 183, 5,.8)"
                            : "none",
                        }}
                        id={`section-${index}`}
                      >
                        <div className="paragraphe-titre">{el.titre}</div>
                        {el?.paragraphes?.map((element, id) => (
                          <>
                            <div
                              key={id}
                              className="paragraphe"
                              dangerouslySetInnerHTML={{ __html: element }}
                            ></div>
                          </>
                        ))}
                      </div>
                    ))}
                  </div>
                ) : (
                  <></>
                )}
              </div>
              <div
                id="view-field-code"
                style={{ display: !switchView ? "none" : "block" }}
              >
                <textarea
                  style={{
                    width: "96%",
                    marginLeft: "2%",
                    marginTop: "5px",
                    height: "90%",
                  }}
                  value={JSONcode}
                ></textarea>
                <button>Copier</button>
                <button>
                  <a
                    className="liste-sommaire"
                    href={globalThis?.window?.URL?.createObjectURL(
                      new Blob([JSONcode], { type: "application/json" })
                    )}
                    download={`${downloadLink}.json`}
                  >
                    Enregistrer
                  </a>
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
